In [1]:
import numpy as np

# Three ways to create arrays
a = np.array([10, 20, 30, 40, 50])
b = np.zeros(5)
c = np.ones(5)
d = np.arange(0, 50, 10)
e = np.linspace(0, 1, 5)

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [10 20 30 40 50]
b: [0. 0. 0. 0. 0.]
c: [1. 1. 1. 1. 1.]
d: [ 0 10 20 30 40]
e: [0.   0.25 0.5  0.75 1.  ]


In [4]:
# YOUR TURN — complete these without looking anything up
# 1. Create an array of integers from 1 to 10
q1 = np.arange(1,11,1)

# 2. Create an array of 6 evenly spaced floats between 0 and 100
q2 = np.linspace(0,100,6)

# 3. Create an array of ten zeros
q3 = np.zeros(10)

print(q1, q2, q3)

[ 1  2  3  4  5  6  7  8  9 10] [  0.  20.  40.  60.  80. 100.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 1D vs 2D vs 3D
arr_1d = np.array([1, 2, 3, 4, 6])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

print("1D shape:", arr_1d.shape)
print("2D shape:", arr_2d.shape)
print("3D shape:", arr_3d.shape)

print("\n1D ndim:", arr_1d.ndim)
print("2D ndim:", arr_2d.ndim)
print("3D ndim:", arr_3d.ndim)

print("\nTotal elements in 2D:", arr_2d.size)
print("Data type:", arr_2d.dtype)

1D shape: (5,)
2D shape: (2, 3)
3D shape: (2, 2, 2)

1D ndim: 1
2D ndim: 2
3D ndim: 3

Total elements in 2D: 6
Data type: int64


In [6]:
# What will these print? Predict FIRST, then run
mystery_1 = np.ones((3, 4))
mystery_2 = np.zeros((2, 3, 4))

print(mystery_1.shape)   # your prediction:
print(mystery_2.size)    # your prediction:
print(mystery_2.ndim)    # your prediction:

(3, 4)
24
3


In [7]:
arr = np.arange(12)
print("Original:", arr)
print("Shape:", arr.shape)

# Reshape into different configurations
as_2d   = arr.reshape(3, 4)
as_2d_b = arr.reshape(4, 3)
as_3d   = arr.reshape(2, 2, 3)

print("\nAs (3,4):\n", as_2d)
print("\nAs (4,3):\n", as_2d_b)
print("\nAs (2,2,3):\n", as_3d)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

As (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

As (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

As (2,2,3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [8]:
arr = np.arange(12)

r1 = arr.reshape(3, -1)   # 3 rows, NumPy picks columns
r2 = arr.reshape(-1, 4)   # NumPy picks rows, 4 columns
r3 = arr.reshape(2, -1, 3)  # NumPy picks the middle dimension

print("reshape(3,-1):", r1.shape)
print("reshape(-1,4):", r2.shape)
print("reshape(2,-1,3):", r3.shape)

reshape(3,-1): (3, 4)
reshape(-1,4): (3, 4)
reshape(2,-1,3): (2, 2, 3)


In [11]:
arr = np.arange(10)

# This will throw an error. Why? Fix it two different ways.
broken = arr.reshape(5,2)

In [12]:
# Create a 1D array of 24 elements, then reshape it into:
base = np.arange(24)

shape_a = base.reshape(6,4)   # (6, 4)
shape_b = base.reshape(2,3,4)   # (2, 3, 4)
shape_c = base.reshape(4,-1)   # (4, -1)  — what does this give you?

print(shape_a.shape, shape_b.shape, shape_c.shape)

(6, 4) (2, 3, 4) (4, 6)


In [15]:
test_arr = np.array([[1., 0., 0.],
 [0., 1., 2.]])

print(test_arr.shape)

(2, 3)
