In [9]:
import numpy as np

#### View vs Copy (Recap)
| Operation | View or Copy? |
| :--- | :---: |
| reshape() | View |
| Slicing a[1:4] | View |
| a.copy() | Copy |
| Boolean masking a[a > 2] | Copy | 
| Fancy indexing a[[0,2,4]] | Copy |

#### Fancy Indexing
Pass a list of indices to select elements in any order.

The output order **follows the index array**, not the original array's order. So fancy indexing lets you:

- Pick any elements
- In **any order you want**
- Even repeat elements (e.g. a[[0, 0, 2]] is valid)

In [42]:
a = np.array([10, 20, 30, 40, 50])
print("a = np.array([10, 20, 30, 40, 50])\t=>\t",a)
print("a[[0, 2, 4]]\t\t\t=>\t\t",a[[0, 2, 4]] )     # → [10, 30, 50]
print( "a[[4, 1, 3]]\t\t\t=>\t\t",a[[4, 1, 3]] )    # → [50, 20, 40]  order follows index array

a = np.array([10, 20, 30, 40, 50])	=>	 [10 20 30 40 50]
a[[0, 2, 4]]			=>		 [10 30 50]
a[[4, 1, 3]]			=>		 [50 20 40]


#### 2D — picks coordinate pairs, not a subgrid:

In [49]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print("""a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])\t =>\n""",a)

print("\na[[0, 2], [1, 2]]\t\t=>\t\t",a[[0, 2], [1, 2]])   # → (row0,col1), (row2,col2) → [20, 90]
print("""\n[0, 2] are the row indices and [1, 2] are the column indices.
(row0,col1), (row2,col2) → [20, 90]""")
#[0, 2] are the row indices and [1, 2] are the column indices. 

a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])	 =>
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

a[[0, 2], [1, 2]]		=>		 [20 90]

[0, 2] are the row indices and [1, 2] are the column indices.
(row0,col1), (row2,col2) → [20, 90]


#### Broadcasting
NumPy stretches arrays with smaller shapes to match larger ones — without copying memory.

**Rule**: Align shapes from the right. Each dimension pair must be:

- **1. Equal**, or
- **2. One of them is 1**

All pairs must pass — not just the rightmost.

- (2, 3) + (3,)   ✅
- (2, 3) + (1,)   ✅  
- (2, 3) + scalar ✅
- (2, 3) + (2,)   ❌

NumPy aligns shapes from the right side. So for (2, 3) + (3,):<br>
`a → 2  3`<br>
`b →    3 `<br>
The rightmost dimensions are 3 and 3 — they match ✅

For (2, 3) + (2,):<br>
`a → 2  3`<br>
`b →    2`<br>
 The rightmost dimensions are 3 and 2 — they don't match ❌

Now look at (2, 3) + (1,):<br>
`a → 2  3`<br>
`b →    1`<br>
 3 and 1 — this works! ✅


- (4, 3) + (4, 3)  ✅  both equal
- (4, 3) + (1, 3)  ✅  4 vs 1 → one is 1 ✅, 3 vs 3 → equal ✅
- (4, 3) + (4, 1)  ✅  4 vs 4 → equal ✅, 3 vs 1 → one is 1 ✅
- (4, 3) + (3, 1)  ❌  4 vs 3 → neither equal nor 1

In [62]:
a = np.array([1, 2, 3])
print("a = np.array([1, 2, 3])\t=>\t",a)
print("a + 10\t\t\t=>\t",a + 10) # → [11, 12, 13]
# NumPy stretches the scalar 10 to match the shape of a, as if it became [10, 10, 10], and then adds element-wise
print("NumPy stretches the scalar 10 to match the shape of a, as if it became [10, 10, 10], and then adds element-wise")


a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

print("""\na = np.array([[1, 2, 3],
              [4, 5, 6]])\t=>\n""",a)

b = np.array([10, 20, 30]) # shape (3,)
print("\nb = np.array([10, 20, 30])\t=>\t",b)

print("\na + b\t=>\n",a + b)  #-> [[11 22 33]
                              #   [14 25 36]]
print("""\nb gets broadcast across each row of a, as if it were stretched to:
[[10, 20, 30],
[10, 20, 30]]""")
#b gets broadcast across each row of a, as if it were stretched to:
#[[10, 20, 30],
# [10, 20, 30]]

#When does it fail?
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

b = np.array([10, 20])      # shape (2,)

#print(a + b)


a = np.array([1, 2, 3])	=>	 [1 2 3]
a + 10			=>	 [11 12 13]
NumPy stretches the scalar 10 to match the shape of a, as if it became [10, 10, 10], and then adds element-wise

a = np.array([[1, 2, 3],
              [4, 5, 6]])	=>
 [[1 2 3]
 [4 5 6]]

b = np.array([10, 20, 30])	=>	 [10 20 30]

a + b	=>
 [[11 22 33]
 [14 25 36]]

b gets broadcast across each row of a, as if it were stretched to:
[[10, 20, 30],
[10, 20, 30]]


#### np.where
Vectorized if-else applied element-wise.

  np.where takes 3 arguments:

   e.g. np.where(a > 10, a, 0)
1. A **condition** : a > 10
2. A value to use **where condition is True** : a
3. A value to use **where condition is False** : 0

In [66]:
# np.where(condition, value_if_true, value_if_false)
a = np.array([10, 25, 3, 47, 8, 15])
print("a = np.array([10, 25, 3, 47, 8, 15])\t=>\t",a)
print("\nnp.where(a > 10, a, 0)\t\t\t=>\t",np.where(a > 10, a, 0))   # → [0, 25, 0, 47, 0, 15]

a = np.array([10, 25, 3, 47, 8, 15])	=>	 [10 25  3 47  8 15]

np.where(a > 10, a, 0)			=>	 [ 0 25  0 47  0 15]


#### np.argmax
Returns the index of the maximum value, not the value itself.

ML use case: output of a classifier → np.argmax(probabilities) gives predicted class.

In [78]:
a = np.array([10, 25, 3, 47, 8, 15])
print("a = np.array([10, 25, 3, 47, 8, 15])\t=>\t",a)
print("np.argmax(a)\t=>\t",np.argmax(a) )         # → 3

a = np.array([[10, 25, 3],
              [47, 8, 15]])
print("""\n2D array:
a = np.array([[10, 25, 3],
              [47, 8, 15]])\t=>\n""",a)
# 2D with axis:
print("np.argmax(a, axis=0) \t=>\t",np.argmax(a, axis=0))  # index of max per column (collapse rows)
print("np.argmax(a, axis=1)\t=>\t",np.argmax(a, axis=1))  # index of max per row (collapse columns)
#This is a 2D array, so argmax along an axis returns one index per column or per row — not a single number.
print("\nThis is a 2D array, so argmax along an axis returns one index per column or per row — not a single number.")
print("""
      col0  col1  col2
row0:  10    25    3
row1:  47    8     15
For each column, which row has the max?

col0: max is 47 → row 1
col1: max is 25 → row 0
col2: max is 15 → row 1

So axis=0 → [1, 0, 1]""")

a = np.array([10, 25, 3, 47, 8, 15])	=>	 [10 25  3 47  8 15]
np.argmax(a)	=>	 3

2D array:
a = np.array([[10, 25, 3],
              [47, 8, 15]])	=>
 [[10 25  3]
 [47  8 15]]
np.argmax(a, axis=0) 	=>	 [1 0 1]
np.argmax(a, axis=1)	=>	 [1 0]

This is a 2D array, so argmax along an axis returns one index per column or per row — not a single number.

      col0  col1  col2
row0:  10    25    3
row1:  47    8     15

For each column, which row has the max?

col0: max is 47 → row 1
col1: max is 25 → row 0
col2: max is 15 → row 1

So axis=0 → [1, 0, 1]


#### Stacking & Splitting
Mental model: vstack adds rows, hstack adds columns.
- "Stacking vertically" means placing one on top of the other, not interleaving columns.
- "Stacking horizontally" means stacking the arrays horizontally

In [95]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a = np.array([1, 2, 3])\t=>\t",a)
print("b = np.array([4, 5, 6])\t=>\t",b)

print("\nnp.vstack([a, b])\t=>\tshape (2,3) — adds rows=>\t\n",np.vstack([a, b]))   # → [[1,2,3], [4,5,6]]  shape (2,3) — adds rows
print("\nnp.hstack([a, b])\t=>\tshape (6,) — adds columns\t=>\t",np.hstack([a, b]) )  # → [1,2,3,4,5,6]        shape (6,) — adds columns

a = np.array([1, 2, 3, 4, 5, 6])
print("\na = np.array([1, 2, 3, 4, 5, 6])\t=>\t",a)
print("np.split(a, 3)\t\t\t\t=>\t",np.split(a, 3))      # → [array([1,2]), array([3,4]), array([5,6])]
print("[1, 2, 3, 4, 5, 6] divided into 3 equal chunks ")

a = np.array([1, 2, 3])	=>	 [1 2 3]
b = np.array([4, 5, 6])	=>	 [4 5 6]

np.vstack([a, b])	=>	shape (2,3) — adds rows=>	
 [[1 2 3]
 [4 5 6]]

np.hstack([a, b])	=>	shape (6,) — adds columns	=>	 [1 2 3 4 5 6]

a = np.array([1, 2, 3, 4, 5, 6])	=>	 [1 2 3 4 5 6]
np.split(a, 3)				=>	 [array([1, 2]), array([3, 4]), array([5, 6])]
[1, 2, 3, 4, 5, 6] divided into 3 equal chunks 
