In [13]:
import numpy as np


---
## Exercise 1 — Print the NumPy version

**Concept:** Verifying NumPy is installed and checking the version.

In [1]:
print(np.__version__)

2.3.5


---
## Exercise 2 — Create a null vector of size 10

**Concept:** `np.zeros` creates a float64 array by default — notice the `0.` output, not `0`.

In [2]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Key insight:** `np.zeros` produces `float64` by default — values display as `0.` not `0`.  
To get integers: `np.zeros(10, dtype=int)`

---
## Exercise 3 — Create a null vector of size 10, set the 5th element to 1

**Concept:** Zero-based indexing — the 5th element is at index 4.

In [3]:
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Key insight:** Zero-based indexing — "5th element" = index 4. The value `1` is stored as `1.` because the array dtype is float64.

---
## Exercise 4 — Create a vector with values ranging from 10 to 49

**Concept:** `np.arange(start, stop)` — stop is **exclusive**.

In [5]:
a = np.arange(10, 50)
print(a)
print(a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int64


**Key insight:** `np.arange(start, stop, step=1)` — the stop value is **exclusive**.  
Returns `int64` by default (no decimal points).

---
## Exercise 5 — Reverse a vector (first element becomes last)

**Concept:** Slicing with `[::-1]` reverses any array.

In [6]:
a = np.arange(10, 50)
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**Key insight:** `[::-1]` means step = -1, so NumPy walks the array backwards.  
Same pattern works on Python lists too.

---
## Exercise 6 — Create a 3x3 matrix with values 0 to 8

**Concept:** `np.arange` + `reshape` to build a 2D matrix.

In [7]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Key insight:** `np.arange(9)` produces `[0..8]`, and `reshape(3,3)` arranges them row by row.  
The grid looks like:
```
0  1  2
3  4  5
6  7  8
```

---
## Exercise 7 — Find indices of non-zero elements

**Concept:** `np.nonzero` returns the **indices** of non-zero elements (not the values themselves).

In [8]:
a = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(a))

(array([0, 1, 4]),)


**Key insight:** `np.nonzero` returns a **tuple** of arrays — one per dimension.  
For a 1D array: `(array([0, 1, 4]),)` → non-zero values live at indices 0, 1, and 4.  
The tuple structure supports multi-dimensional arrays (one index array per axis).

Difference from boolean masking:
- Boolean mask: `a[a != 0]` → returns the **values** `[1, 2, 4]`
- `np.nonzero(a)` → returns the **indices** `(array([0, 1, 4]),)`

---
## Exercise 8 — Create a 3x3 identity matrix

**Concept:** `np.eye(n)` creates an identity matrix — 1s on the diagonal, 0s elsewhere.

In [9]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Key insight:** The identity matrix is fundamental in linear algebra — multiplying any matrix by it returns the original matrix (like multiplying a number by 1).  
`np.eye` produces `float64` by default.

Grid:
```
1.  0.  0.
0.  1.  0.
0.  0.  1.
```

---
## Exercise 9 — Create a 3x3 array with random values, print min, max, mean

**Concept:** `np.random.random` generates floats in `[0, 1)`. Aggregate operations on random data.

In [11]:
a = np.random.random((3, 3))
print(a)
print(a.min(), a.max(), a.mean())

[[0.54945543 0.69287885 0.64531974]
 [0.50932872 0.71675017 0.16420869]
 [0.78876169 0.31222309 0.20872711]]
0.16420868709028547 0.7887616925136858 0.5097392764230879


**Key insight:** `np.random.random((3,3))` — the argument is a **shape tuple**, not two separate ints.  
All values fall in `[0.0, 1.0)`, so:
- `min` ≈ close to 0
- `max` ≈ close to 1
- `mean` ≈ ~0.5 (averages out over many values)

---
## Exercise 10 — Create a random array and subtract the mean (mean centering)

**Concept:** Mean centering — shifting data so the mean becomes 0.

In [12]:
a = np.random.random((3, 3))
print(a - a.mean())

[[ 0.33864349  0.16099395  0.20073881]
 [-0.21545892  0.11830469 -0.43442226]
 [ 0.43023892 -0.5218159  -0.07722277]]


**Key insight:** Subtracting the mean from every element **centers** the data around 0.  
- Values that were below the mean → negative
- Values that were above the mean → positive
- The new mean ≈ 0 (tiny floating point error)

This is a foundational preprocessing step in ML — used in normalization, PCA, and neural network input scaling.

---
## Session Summary — Day 4

| Exercise | Topic | Key Concept |
|----------|-------|-------------|
| 1 | Version check | `np.__version__` |
| 2 | Null vector | `np.zeros` → float64 by default |
| 3 | Set element | Zero-based indexing |
| 4 | Range vector | `np.arange` — stop is exclusive |
| 5 | Reverse | `[::-1]` slice trick |
| 6 | 3x3 matrix | `arange` + `reshape` |
| 7 | Non-zero indices | `np.nonzero` returns indices, not values |
| 8 | Identity matrix | `np.eye` |
| 9 | Random + aggregates | `np.random.random`, `min/max/mean` |
| 10 | Mean centering | Broadcasting scalar subtraction |
