In [2]:
import numpy as np

# Day 5 Numpy Exercises 11–20

## Warm-up: Cold Recall from Day 4

1. `a = np.zeros((3,4))` → `a.dtype` is `float64`, and `a[0,0]` prints as `0.` (not `0`), since it's a float.
2. `b = a[1:3, :]` is a **view**, not a copy — slicing shares memory with the original array. So `b[0,0] = 99` changes `a[1,0]` too.
3. Broadcasting: `(3,4)` + `(4,)` works (trailing dims match: 4==4). `(3,4)` + `(3,)` fails (trailing dims 4 vs 3 don't match, and neither is 1).


In [5]:
# Warm-up verification
a = np.zeros((3, 4))
print("dtype:", a.dtype)
print("a[0,0]:", a[0, 0])

b = a[1:3, :]
b[0, 0] = 99
print("a[1,0] after modifying view b:", a[1, 0])

# Broadcasting checks
try:
    result = np.ones((3, 4)) + np.ones((4,))
    print("(3,4)+(4,) works, shape:", result.shape)
except ValueError as e:
    print("(3,4)+(4,) failed:", e)

try:
    result = np.ones((3, 4)) + np.ones((3,))
    print("(3,4)+(3,) works, shape:", result.shape)
except ValueError as e:
    print("(3,4)+(3,) failed:", e)

dtype: float64
a[0,0]: 0.0
a[1,0] after modifying view b: 99.0
(3,4)+(4,) works, shape: (3, 4)
(3,4)+(3,) failed: operands could not be broadcast together with shapes (3,4) (3,) 


---
## Exercise 11 — Create a 3x3 identity matrix

**Concept:** `np.eye(n)` creates an identity matrix — 1s on the diagonal, 0s elsewhere.

In [6]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Key insight:** A single argument to `np.eye` gives a square identity matrix — `np.eye(3)` is equivalent to `np.eye(3, 3)`.
`np.eye` produces `float64` by default, same as `np.zeros`.

---
## Exercise 12 — Create a 3x3x3 array with random values

**Concept:** `np.random.random(shape)` extends naturally to any number of dimensions — the shape tuple just needs a third value.

In [7]:
a = np.random.random((3, 3, 3))
print(a)
print(a.shape)

[[[0.66260366 0.44728085 0.88624733]
  [0.56778371 0.09586783 0.38129361]
  [0.56578001 0.76752153 0.85267236]]

 [[0.63178045 0.29415569 0.34955629]
  [0.51157262 0.42474409 0.20725134]
  [0.32391724 0.9819138  0.20520931]]

 [[0.78060867 0.17956454 0.91848214]
  [0.94760662 0.13276931 0.91062254]
  [0.17943373 0.56657673 0.07604864]]]
(3, 3, 3)


**Key insight:** The shape tuple `(3,3,3)` produces a 3D array — think of it as 3 stacked 3x3 matrices.
NumPy doesn't cap the number of dimensions; the same `random((...))` pattern scales to 4D, 5D, etc.

---
## Exercise 13 — Create a 10x10 array with random values and find the min and max

**Concept:** Array methods `.min()` and `.max()` reduce the whole array to a single scalar, regardless of shape.

In [8]:
a = np.random.random((10, 10))
print(a.min(), a.max())

0.0031666506408700723 0.9769330354247342


**Key insight:** `.min()`/`.max()` are array **methods** and take no arguments — the array supplies itself as the operand.
The functional form `np.min(a)` / `np.max(a)` does the same thing but needs the array passed explicitly; calling `np.min()` alone with nothing to reduce raises an error.

---
## Exercise 14 — Create a random vector of size 30 and find the mean value

**Concept:** `np.random.random` also accepts a single int as shape for a 1D vector.

In [10]:
a = np.random.random(30)
print(a.mean())

0.5188352243286168


**Key insight:** `np.random` is a **module**, not a callable — the random-generating function lives inside it as `np.random.random(...)`. Writing `np.random()` tries to call the module itself and errors out.
`.mean()` averages all 30 values into one scalar.

---
## Exercise 15 — Create a 2D array with 1 on the border and 0 inside

**Concept:** Combining full-array initialization (`np.ones`) with interior slicing (`1:-1`) to build border patterns of any size.

In [9]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Key insight:** The slice `1:-1` on an axis skips the first and last index, isolating everything in between.
Applied to both axes at once — `a[1:-1, 1:-1]` — it carves out exactly the interior block, leaving the outer border of 1s untouched. This generalizes to any array shape, unlike manually typing out rows.

---
## Exercise 16 — How to add a border (filled with 0's) around an existing array?

**Concept:** `np.pad` wraps extra values around an existing array without modifying it in place.

In [11]:
a = np.random.random((5, 5))
b = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a.shape, "->", b.shape)
print(b)

(5, 5) -> (7, 7)
[[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.82174371 0.21698504 0.24627265 0.4845713  0.32529111
  0.        ]
 [0.         0.04756753 0.24717636 0.88411983 0.25460611 0.15591909
  0.        ]
 [0.         0.36833922 0.45519243 0.85919626 0.24863364 0.93963364
  0.        ]
 [0.         0.70852444 0.88706319 0.18203581 0.48950453 0.84656813
  0.        ]
 [0.         0.10124197 0.09634325 0.90236346 0.19775364 0.51323295
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]


**Key insight:** `np.pad`'s signature is `np.pad(array, pad_width, mode='constant', constant_values=0)` — `mode` is a **string** describing the padding strategy, and the fill value is a separate keyword, `constant_values`.
Padding of 1 adds a row/column on **each** side of every dimension, so a (5,5) array becomes (7,7): 5 + 1 + 1 = 7.

---
## Exercise 17 — What is the result of the following expressions?

**Concept:** NaN (Not a Number) has special, non-intuitive rules for arithmetic, comparison, and identity.

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [12]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**Key insight:**
- **Arithmetic propagation:** any arithmetic operation involving NaN (`+`, `-`, `*`, `/`) produces NaN — even `0 * np.nan` doesn't "cancel" to 0.
- **Comparisons return False:** every comparison operator (`==`, `>`, `<`, `>=`, `<=`) involving NaN returns `False`, since NaN is not just unequal but *incomparable* — including `np.inf > np.nan`.
- **Identity short-circuits containers:** `np.nan in set([np.nan])` is `True` because Python's `in` checks object identity (`is`) before falling back to `==` — the same NaN object matches itself by identity.
- **Floating-point precision:** `0.3 == 3 * 0.1` is `False` because `3 * 0.1` isn't exactly representable as `0.3` in binary floating point. Use `np.isclose()` for float comparisons instead of `==`.

---
## Exercise 18 — Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

**Concept:** `np.diag(v, k)` builds a new 2D array by placing a 1D array of values along a diagonal, offset by `k`.

In [13]:
a = np.diag([1, 2, 3, 4], k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**Key insight:** `np.diag` is dual-purpose — pass it a 2D array and it *extracts* the diagonal; pass it a 1D array and it *builds* a new matrix from it. That's different from `np.diagonal`, which only extracts.
Negative `k` shifts the diagonal below the main diagonal; positive `k` shifts above. The resulting matrix size is inferred from the length of the input — 4 values need a 5x5 matrix.

---
## Exercise 19 — Create an 8x8 matrix and fill it with a checkerboard pattern

**Concept:** 2D slicing with a step (`a[start::step, start::step]`) selects individual cells across both axes at once, not entire rows.

In [ ]:
a = np.zeros((8, 8))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

**Key insight:** A checkerboard cell `(row, col)` is `1` exactly when `row + col` is odd. Slicing only one axis (e.g. `a[::2] = 1`) sets **entire rows**, producing stripes instead of a checkerboard.
The two groups where `row + col` is odd are (even row, odd col) and (odd row, even col) — hence the two slice assignments on both axes together.

---
## Exercise 20 — Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

**Concept:** `np.unravel_index(flat_index, shape)` converts a flat (1D) position into multi-dimensional coordinates, based on NumPy's default row-major memory layout.

In [ ]:
idx = np.unravel_index(99, (6, 7, 8))
print(idx)

**Key insight:** The "100th element" means flat index 99 (0-based). `unravel_index` takes the index **first** and the shape **second** — and only needs the shape tuple, not an actual array, since it's purely a coordinate calculation.

---
## Session Summary — Day 5

| Exercise | Topic | Key Concept |
|----------|-------|-------------|
| 11 | Identity matrix | `np.eye` |
| 12 | 3D random array | `np.random.random` with a 3-tuple shape |
| 13 | Min/max of 2D array | `.min()`/`.max()` methods |
| 14 | Random vector + mean | `np.random` module vs. `np.random.random()` function |
| 15 | Border pattern (1s/0s) | `np.ones` + interior slicing `[1:-1, 1:-1]` |
| 16 | Padding an array | `np.pad` — `mode` vs. `constant_values` |
| 17 | NaN behavior | Arithmetic propagation, comparison → False, identity in `in`, float precision |
| 18 | Diagonal offset matrix | `np.diag(v, k)` — builds vs. extracts |
| 19 | Checkerboard pattern | 2D step-slicing on both axes |
| 20 | Flat index → coordinates | `np.unravel_index(index, shape)` |
