# Day 6: NumPy — Fancy Indexing & Dimension Rules

**Recap:** Day 5 covered array creation, attributes, indexing/slicing, reshape, view vs copy, boolean masking, aggregates, axis ops, and 100 NumPy Exercises 1–10.

**Today's focus:** fancy indexing with lists, and the rule for when indexing drops vs keeps a dimension.

Setup array used throughout:


In [1]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Part 1: Fancy indexing basics

Indexing has two independent parts separated by the comma: `a[rows, cols]`.

- A **slice** (`1:`, `:2`) selects a contiguous range, in order.
- A **list** (`[0, 2]`) is *fancy indexing* — it selects exact positions, **in the order given**, and can repeat entries.

### Exercise 1: `a[1:, [0, 2]]`
Rows 1: → rows 1 and 2. Columns `[0, 2]` → column 0 then column 2, from those rows.


In [2]:
a[1:, [0, 2]]

array([[ 4,  6],
       [ 8, 10]])

> **Key insight:** Fancy indexing with a list picks *exact positions in the order listed* — not a range, and not necessarily sorted. `[2, 0]` would reverse the column order.

### Exercise 2: `a[:2, [3, 1]]`
Two mistakes to watch for here:
1. `:2` is exclusive — rows 0 and 1 only, **not** row 2.
2. `[3, 1]` returns column 3 first, then column 1 — order matches the list, not ascending.


In [3]:
a[:2, [3, 1]]

array([[3, 1],
       [7, 5]])

> **Key insight:** The exclusive-stop rule from `np.arange` (stop is not included) applies to *any* slice, including row/column slices in indexing.

### Exercise 3: `a[:1, [2, 0, 2]]`
Fancy indexing can repeat entries — `2` appears twice in the list, so column 2 appears twice in the output.


In [4]:
a[:1, [2, 0, 2]]

array([[2, 0, 2]])

> **Key insight:** Row 0 happens to equal its own column indices (`[0,1,2,3]`), so picking columns `2,0,2` gives values `2,0,2` — a coincidence of this particular array, not a general rule.

---

## Part 2: Integer index drops a dimension, slice/list keeps it

**Core rule:** An **integer** index says "give me exactly this one thing, drop the wrapper" → removes that axis.
A **slice or list** says "give me a sub-collection along this axis" → keeps the axis, even if only one element survives.

| Expression | Index type | Result shape | Axis dropped? |
|---|---|---|---|
| `a[0]` | integer | `(4,)` | row axis dropped |
| `a[0:1]` | slice | `(1, 4)` | row axis kept (size 1) |
| `a[:, 0]` | integer | `(3,)` | column axis dropped |
| `a[:, 0:1]` | slice | `(3, 1)` | column axis kept (size 1) |
| `a[0, 0]` | integer, integer | `()` | both dropped (scalar) |
| `a[[0]]` | list (fancy) | `(1, 4)` | row axis kept (size 1) — list behaves like slice |


In [5]:
checks = {
    "a[0]": a[0],
    "a[0:1]": a[0:1],
    "a[:, 0]": a[:, 0],
    "a[:, 0:1]": a[:, 0:1],
    "a[0, 0]": a[0, 0],
    "a[[0]]": a[[0]],
}

for expr, result in checks.items():
    shape = np.shape(result)
    print(f"{expr:12s} -> shape {shape}")

a[0]         -> shape (4,)
a[0:1]       -> shape (1, 4)
a[:, 0]      -> shape (3,)
a[:, 0:1]    -> shape (3, 1)
a[0, 0]      -> shape ()
a[[0]]       -> shape (1, 4)


### Practice: predict the shape (worked through live, all correct on first try)

Array: `a` shape `(3, 4)`

| # | Expression | Predicted shape | Verified |
|---|---|---|---|
| 1 | `a[2]` | `(4,)` | ✅ |
| 2 | `a[2:3]` | `(1, 4)` | ✅ |
| 3 | `a[:, [1, 3]]` | `(3, 2)` | ✅ |
| 4 | `a[1, :]` | `(4,)` | ✅ |
| 5 | `a[1:2, 1:2]` | `(1, 1)` | ✅ |


In [6]:
practice = {
    "a[2]": a[2],
    "a[2:3]": a[2:3],
    "a[:, [1, 3]]": a[:, [1, 3]],
    "a[1, :]": a[1, :],
    "a[1:2, 1:2]": a[1:2, 1:2],
}

for expr, result in practice.items():
    print(f"{expr:16s} -> {result}  shape {np.shape(result)}")

a[2]             -> [ 8  9 10 11]  shape (4,)
a[2:3]           -> [[ 8  9 10 11]]  shape (1, 4)
a[:, [1, 3]]     -> [[ 1  3]
 [ 5  7]
 [ 9 11]]  shape (3, 2)
a[1, :]          -> [4 5 6 7]  shape (4,)
a[1:2, 1:2]      -> [[5]]  shape (1, 1)


## Summary

- **Fancy indexing** (passing a list) selects exact positions in the given order and allows repeats — unlike a slice, which is a contiguous, ordered range.
- **Exclusive stop** applies to every slice, not just `np.arange`.
- **Integer index → drops a dimension. Slice or list index → keeps it** (size 1 if only one element survives). This matters later for broadcasting and stacking, where consistent shapes matter.

## Next session
Broadcasting rules, vectorized math, `np.where`, `np.argmax`, stacking/splitting — then continue 100 NumPy Exercises (11+).
